name: Nicholas Frederick
markdown: kramdown
title: My Resume
theme_skin: blue


sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development